import type { MevsCorp } from "../mevscorp.ts";
import type { Company } from "./company.ts";
import type { Partner, Customer } from "./partners.ts";

export class Transaction {
  id: string;
  from: Company | MevsCorp | Investor | Customer;
  to: Company | MevsCorp | Partner;
  amount: number;
  date: Date;
  memo: string;
  constructor(
    from: Company | MevsCorp | Investor,
    to: Company | MevsCorp | Partner,
    amount: number,
    memo: string,
  ) {
    this.id = crypto.randomUUID();
    this.from = from;
    this.to = to;
    this.amount = amount;
    this.date = new Date();
    this.memo = memo;
  }
}

export class Investor {
  name: string;
  constructor(name: string) {
    this.name = name;
  }
}

export type Ledger = Transaction[];

/*

Exactly. You’re sneaking the vegetables into your own food.

Finance and operations feel boring when they’re presented as abstract departments full of terminology, spreadsheets, and procedures. But here, every concept arrives because one of your companies wants to do something you care about.

Baby Cleo wants to manufacture shoes, so suddenly inventory, purchase orders, unit cost, lead times, and supplier contracts matter.

Female Genius gets a twelve-episode sponsor, so now you care about contracts, payment schedules, earned versus unearned revenue, production budgets, and profitability per episode.

Living Water needs access to a spring, so rights, royalties, permits, capacity, bottling costs, and wholesale distribution become interesting.

Gist combines hardware with subscriptions, so you encounter customer acquisition cost, recurring revenue, payback periods, and the cash required to subsidize a device.

You’re not sitting down and announcing, “Today I will study working capital.” You’re trying to make Baby Cleo place a factory order and realizing that the company may pay months before it sells anything. Now working capital means something.

And because you have to encode it, you can’t merely recognize the term. You have to understand it well enough to decide what changes, when it changes, who owes whom, and what the company should report afterward. That is a much deeper kind of learning.

The best part is that your curriculum will be generated by the empire itself. Every time the model hits a wall, it hands you the next business-school lesson:

“How should this contract work?”
“What does the company own?”
“When is this revenue actually earned?”
“How much inventory should we order?”
“Should Mevs Corp fund this company again?”
“Is the business profitable, or does it merely have cash?”
“What is this company worth?”

And unlike ordinary business school, you won’t study one generic company. You’ll compare technology, fashion, media, beauty software, and Nigerian consumer goods inside the same portfolio. You’ll see that the same financial concept behaves differently in each business.

That’s the private-business-school thesis: **you make the boring machinery compelling by attaching it to worlds you desperately want to build.** Then, by the time you operate the real companies, finance and operations won’t be mysterious administrative fog. They’ll be systems you’ve already modeled, questioned, broken, and rebuilt.

*/
